<?php

namespace CropsEvents;

class EventFields
{
    public function defineFields()
    {
        if (function_exists('acf_add_local_field_group')) {

            acf_add_local_field_group(array(
                'key' => 'group_6995ebf6aa381',
                'title' => 'Event',
                'fields' => array(
                    array(
                        'key' => 'field_6995ee9df1566',
                        'label' => 'Informations générales',
                        'name' => 'event_global_informations',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6995eda1fc23c',
                                'label' => 'Description de l\'événement',
                                'name' => 'event_description',
                                'aria-label' => '',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'allow_in_bindings' => 1,
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                            array(
                                'key' => 'field_6995ebf62d338',
                                'label' => 'Début de l\'événement',
                                'name' => 'event_begin_date',
                                'aria-label' => '',
                                'type' => 'date_time_picker',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'j F Y H:i',
                                'return_format' => 'j F Y H:i',
                                'first_day' => 1,
                                'default_to_current_date' => 0,
                                'allow_in_bindings' => 1,
                            ),
                            array(
                                'key' => 'field_6995ec63cbeb2',
                                'label' => 'Fin de l\'événement',
                                'name' => 'event_end_date',
                                'aria-label' => '',
                                'type' => 'date_time_picker',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'j F Y H:i',
                                'return_format' => 'j F Y H:i',
                                'first_day' => 1,
                                'default_to_current_date' => 0,
                                'allow_in_bindings' => 1,
                            ),
                            array(
                                'key' => 'field_6995ee5175823',
                                'label' => 'Lieu de l\'événement',
                                'name' => 'event_location',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 1,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6995efc0d6dec',
                        'label' => 'Informations d\'inscription',
                        'name' => 'event_register_informations',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6995f38457e69',
                                'label' => 'Inscriptions ouvertes',
                                'name' => 'event_is_register_open',
                                'aria-label' => '',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'allow_in_bindings' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                                'ui' => 1,
                            ),
                            array(
                                'key' => 'field_6995f52462123',
                                'label' => 'Date limite d\'inscription',
                                'name' => 'event_register_limit_date',
                                'aria-label' => '',
                                'type' => 'date_time_picker',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'j F Y H:i',
                                'return_format' => 'j F Y H:i',
                                'first_day' => 1,
                                'default_to_current_date' => 0,
                                'allow_in_bindings' => 1,
                            ),
                            array(
                                'key' => 'field_6995f5e48fbae',
                                'label' => 'Nombre de places',
                                'name' => 'event_capacity',
                                'aria-label' => '',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'min' => '',
                                'max' => '',
                                'allow_in_bindings' => 1,
                                'placeholder' => '',
                                'step' => '',
                                'prepend' => '',
                                'append' => 'personnes',
                            ),
                            array(
                                'key' => 'field_6995f6b981982',
                                'label' => 'Gratuit / Payant',
                                'name' => 'event_is_paid',
                                'aria-label' => '',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'allow_in_bindings' => 1,
                                'ui_on_text' => 'Payant',
                                'ui_off_text' => 'Gratuit',
                                'ui' => 1,
                            ),
                            array(
                                'key' => 'field_6995f8db81983',
                                'label' => 'Prix de l\'événement',
                                'name' => 'event_price',
                                'aria-label' => '',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6995f6b981982',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'min' => '',
                                'max' => '',
                                'allow_in_bindings' => 1,
                                'placeholder' => '',
                                'step' => '',
                                'prepend' => '',
                                'append' => '€',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'event',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'seamless',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 1,
                'display_title' => '',
            ));
        }
    }

    public function register()
    {
        add_action('init', [$this, 'defineFields']);
    }
}